#!/bin/bash

source ./dottie/dottie.sh

# Clean old files

# Link files and directories
link bin ~/.local/bin
link kitty ~/.config/kitty
link nvim ~/.config/nvim
link nvim ~/.config/nvim
link tmux ~/.config/tmux

link emacs.d/init.el ~/.emacs.d/init.el
link lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
link pomo/config.json ~/.config/pomo/config.json
link starship.toml ~/.config/starship.toml

# Home and fish configs have to be linked individually
link_contents home ~/
link_contents fish ~/.config/fish/

# Widen config
if [[ -n "$WIDEN" ]]; then
	link widen/bin ~/.local/bin-widen
	link widen/gh/config.yml ~/.config/gh/config.yml
	link widen/gh-dash/config.yml ~/.config/gh-dash/config.yml

	link_contents widen/home ~/
	link_contents widen/fish ~/.config/fish/
else
	link gh/config.yml ~/.config/gh/config.yml
	link gh-dash/config.yml ~/.config/gh-dash/config.yml
fi

# VS Code settings and keybindings
link vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
link vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json

# Finalize and print any errors
finalize
