#!/bin/bash

source ./dottie/dottie.sh

# ~/.config directory
link .config/byte/config.yaml ~/.config/byte/config.yaml
link .config/direnv ~/.config/direnv
link .config/fd ~/.config/fd
link .config/gh-dash/config.yml ~/.config/gh-dash/config.yml
link .config/gh/config.yml ~/.config/gh/config.yml
link .config/ghostty ~/.config/ghostty
link .config/git ~/.config/git
link .config/graphite/aliases ~/.config/graphite/aliases
link .config/graphite/custom-aliases ~/.config/graphite/custom-aliases
link .config/kitty ~/.config/kitty
link .config/starship.toml ~/.config/starship.toml
link .config/task ~/.config/task
link .config/tmux ~/.config/tmux

# Link files and directories
link bin ~/.local/bin
link nvim ~/.config/nvim
link .hammerspoon ~/.hammerspoon
link .skeletons ~/.skeletons

link .ssh/config ~/.ssh/config
link .emacs.d/early-init.el ~/.emacs.d/early-init.el
link .emacs.d/init.el ~/.emacs.d/init.el
link lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
link ngrok/ngrok.yml ~/Library/Application\ Support/ngrok/ngrok.yml

# Some directories need to be partially copied
link_dir home ~/
link_dir .config/fish ~/.config/fish/
# link_dir launchd ~/Library/LaunchAgents/
link_dir nushell ~/Library/Application\ Support/nushell/

# Add custom fonts to the user fonts library
copy_dir personal/fonts ~/Library/Fonts/

# Install remote fonts
curl -sL https://termicons.mskelton.dev/termicons.ttf -o ~/Library/Fonts/termicons.ttf
curl -sL https://github.com/mskelton/vscode-codicons/raw/main/dist/codicon.ttf -o ~/Library/Fonts/codicon.ttf

# Work config
if [[ -f "$HOME/.work" ]]; then
	link work/.config/pomo/config.json ~/.config/pomo/config.json
	link work/bin ~/.local/bin-work
	link_dir work/.config/fish ~/.config/fish/
else
	link .config/pomo/config.json ~/.config/pomo/config.json
	link_dir personal/.config/fish ~/.config/fish/
fi

# VS Code settings and keybindings
link vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
link vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json
link vscode/snippets ~/Library/Application\ Support/Code/User/snippets

# Cursor settings and keybindings
link vscode/settings.json ~/Library/Application\ Support/Cursor/User/settings.json
link vscode/keybindings.json ~/Library/Application\ Support/Cursor/User/keybindings.json
link vscode/snippets ~/Library/Application\ Support/Cursor/User/snippets

# Finalize and print any errors
finalize
