# vim:ft=kitty

new_tab dotfiles
cd ~/dev/dotfiles
launch

new_tab web-alpha
cd ~/dev/web-alpha
launch

new_tab web-beta
cd ~/dev/web-beta
launch

new_tab web
layout tall
cd ~/dev/web-alpha
launch
cd ~/dev/web-data
launch --location=hsplit

new_tab core
cd ~/dev/core
launch

new_tab ramp-inspect
cd ~/dev/ramp-inspect
launch

focus_tab 0
