gui:
  nerdFontsVersion: "3"
  scrollHeight: 20
  theme:
    selectedLineBgColor: ["#364A82"]
    selectedRangeBgColor: ["#364A82"]
keybinding:
  universal:
    pushFiles: "p"
    pullFiles: "P"
  files:
    confirmDiscard: "d"
promptToReturnFromSubprocess: false
