return {
	android_studio = "Android Studio",
	arc = "Arc",
	chat_gpt = "ChatGPT",
	cursor = "Cursor",
	cursor_id = "com.todesktop.230313mzl4w4u92",
	cursor_dev = "Cursor Dev",
	cursor_dev_id = "co.anysphere.cursor.dev",
	chrome = "Google Chrome",
	figma = "Figma",
	finder = "Finder",
	kitty = "kitty",
	linear = "Linear",
	mimestream = "Mimestream",
	notion = "Notion",
	slack = "Slack",
	telegram = "Telegram",
	todoist = "Todoist",
	vscode = "Visual Studio Code",
	zoom = "zoom.us",
	zoom_id = "us.zoom.xos",
}
