return {
	android_studio = "Android Studio",
	arc = "Arc",
	chat_gpt = "ChatGPT",
	cursor = "Cursor",
	chrome = "Google Chrome",
	figma = "Figma",
	finder = "Finder",
	kitty = "kitty",
	linear = "Linear",
	mimestream = "Mimestream",
	notion = "Notion",
	slack = "Slack",
	telegram = "Telegram",
	todoist = "Todoist",
	vscode = "Visual Studio Code",
	zoom = "zoom.us",
}
