'$schema' = 'https://starship.rs/config-schema.json'
add_newline = false

[aws]
disabled = true
symbol = "톛 "

[battery]
discharging_symbol = '󰁺 '

[buf]
symbol = "톜 "

[bun]
disabled = true

[c]
disabled = true
symbol = "퀩 "

[cmake]
disabled = true

[character]
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[r](bold red)'
vimcmd_replace_symbol = '[R](bold red)'
vimcmd_visual_symbol = '[V](bold purple)'

[cmd_duration]
disabled = true

[conda]
disabled = true
symbol = "톝 "

[dart]
disabled = true
symbol = "큎 "

[directory]
read_only = " 킷"

[docker_context]
disabled = true
symbol = "큗 "

[elixir]
symbol = "큠 "

[elm]
symbol = "큡 "

[gcloud]
disabled = true

[git_status]
stashed = ""

[git_branch]
symbol = "큸 "

[golang]
symbol = '큽 '

[guix_shell]
symbol = "톞 "

[haskell]
symbol = "킌 "

[haxe]
symbol = "킍 "

[hg_branch]
symbol = "큸 "

[java]
disabled = true
symbol = "킞 "

[lua]
symbol = '킺 '

[julia]
symbol = "킦 "

[memory_usage]
symbol = "톟 "

[meson]
symbol = "탂 "

[nim]
symbol = "탑 "

[nix_shell]
symbol = "탒 "

[nodejs]
disabled = true
symbol = "탓 "

[os.symbols]
Amazon = "톡 "
Linux = "톦 "
Macos = "퀋 "
NixOS = "탒 "
Ubuntu = "톥 "
Unknown = "톤 "
Windows = "톢 "

[package]
symbol = "톣 "

[python]
symbol = "탼 "

[rlang]
symbol = "탿 "

[ruby]
symbol = "턖 "

[rust]
disabled = true
symbol = "턗 "

[scala]
symbol = "턝 "

[shell]
format = '[$indicator]($style)'
fish_indicator = ''
bash_indicator = 'bsh '
zsh_indicator = 'zsh '
disabled = false

[spack]
symbol = "토 "

[swift]
symbol = '텀 '
disabled = true
