prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open -author:@me involves:@me
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open -author:@me involves:@me
defaults:
  prsLimit: 20
  issuesLimit: 20
  preview:
    open: true
    width: 100
repoPaths:
  mskelton/*: ~/dev/*
keybindings:
pager:
  diff: less
