set -g fish_user_paths $fish_user_paths "$HOME/.local/bin"
set -g fish_user_paths $fish_user_paths "$HOME/.local/bin-work"
set -g fish_user_paths $fish_user_paths "$GOPATH/bin"
set -g fish_user_paths $fish_user_paths "$HOME/.cargo/bin"
set -g fish_user_paths $fish_user_paths "$HOME/.local/npm/bin"
set -g fish_user_paths $fish_user_paths "$HOME/.bun/bun"
set -g fish_user_paths $fish_user_paths "$fzf_base/bin"
set -g fish_user_paths $fish_user_paths "$PYENV_ROOT/bin"
