#+AUTHOR: Mark Skelton
#+PROPERTY: Header-args :tangle init.el
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Package Manager

I'm using [straight.el](https://github.com/radian-software/straight.el#features) as my package manager.

#+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
	(expand-file-name
	"straight/repos/straight.el/bootstrap.el"
	(or (bound-and-true-p straight-base-dir)
	    user-emacs-directory)))
	(bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	(url-retrieve-synchronously
	    "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	    'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

With straight installed, we can install ~use-package~ which is what we'll actually use to configure
all our packages.

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(require 'use-package)
(setq use-package-always-ensure t)
(setq straight-use-package-by-default t)
#+end_src

* Packages

Each package I use is documented in a section below. In general my philosophy for configuring
packages is that each package configuration should be self-contained with as little external
dependency as possible.

** Evil Mode

The only way to make Emacs usable. Without Vim keybindings, it's pretty rough.
Most of these keybindings are direct relationships with my Neovim config.

#+begin_src emacs-lisp
(use-package evil
  :init
  (setq evil-want-C-u-scroll t)
  :config
  (evil-mode 1)
  ;; Keymaps
  (define-key evil-normal-state-map (kbd "SPC fp") 'find-file)
  (define-key evil-normal-state-map (kbd "SPC or") 'reload-config)
  (define-key evil-normal-state-map (kbd ", s") 'save-buffer)
  (define-key evil-normal-state-map (kbd ", w") 'evil-delete-buffer)
  (define-key evil-normal-state-map ";" 'evil-ex))
#+end_src

** Theme

#+begin_src emacs-lisp
(use-package atom-one-dark-theme
  :init
  (load-theme 'atom-one-dark t))
#+end_src

** Org Mode

The package everyone talks about. A bunch of changes are needed to make org
mode keybindings work well with evil mode, but other than that it's pretty great.

#+begin_src emacs-lisp
(use-package org
  :init
  (setq org-emphasis-alist
    '(("*" (bold :family "JetBrains Mono") org-bold)
      ("/" italic)
      ("_" underline)
      ("+" (:strike-through t)))))
#+end_src
 
** Which Key

Probably will get rid of this one soon.

#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 1))
#+end_src

** Dired

On macOS, the ~ls~ command does not support the ~--dired~ option, so instead
we have to use the ~gls~ command from ~coreutils~. While I currently only use macOS
I'm keeping the config platform agnostic.

#+begin_src emacs-lisp
(when (string= system-type "darwin")
  (setq dired-use-ls-dired t
    insert-directory-program "/opt/homebrew/bin/gls"
    dired-listing-switches "-aBhl --group-directories-first"))
#+end_src

* Commands

** Reload Config

Reloads the Emacs config in place.

#+begin_src emacs-lisp
(defun reload-config ()
  "Reload the Emacs config."
  (interactive)
  (load-file "~/.emacs.d/init.el"))
#+end_src

* Keybindings

#+begin_src emacs-lisp
(global-set-key (kbd "<escape>") 'keyboard-escape-quit) ;; Make Escape quit prompts
#+end_src

* Interface

#+begin_src emacs-lisp
;; Due to a bug in Emacs, we have to set the default font to a non-bold version
;; of Operator, and then manually set the bold font when needed.
(set-face-attribute 'default nil :family "JetBrains Mono" :height 150)
(setq-default line-spacing 5)

(tool-bar-mode -1) ;; Hide toolbar
(scroll-bar-mode -1) ;; Hide scrollbar
(menu-bar-mode -1) ;; Hide menu bar
(tooltip-mode -1)
(set-fringe-mode 10) ;; Window padding
(setq ring-bell-function 'ignore) ;; Disable audio bell
(setq inhibit-startup-message t) ;; Disable startup message

(setq default-directory "~/dev/")
#+end_src

* Misc

** Backups

#+begin_src emacs-lisp
(setq backup-directory-alist '(("" . "~/.emacs.d/backup")))
#+end_src

** Custom file

#+begin_src emacs-lisp
(setq custom-file (concat user-emacs-directory "/custom.el"))
#+end_src
